variable = 10
print(type(variable))
variable = float(10.0)
print(type(variable))
variable = bool(True)
print(type(variable))
variable = str("10")
print(type(variable))
variable = list([10,2])
print(type(variable))